export const FETCH_USERS_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_SUBS_REQUEST = 'FETCH_SUBS_REQUEST';
export const FETCH_SUBS_SUCCESS = 'FETCH_SUBS_SUCCESS';
export const FETCH_SUBS_FAILURE = 'FETCH_SUBS_FAILURE';

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';


export const USER_AUTH_LOGIN_REQUEST = 'USER_AUTH_LOGIN_REQUEST';
export const USER_AUTH_LOGIN_SUCCESS = 'USER_AUTH_LOGIN_SUCCESS';
export const USER_AUTH_LOGIN_FAILURE = 'USER_AUTH_LOGIN_FAILURE';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
export const USER_AUTH_REGISTER_REQUEST = 'USER_AUTH_REGISTER_REQUEST';
export const USER_AUTH_REGISTER_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_REGISTER_FAILURE = 'USER_AUTH_FAILURE';

export const SHOW_USER_AUTH_MODAL = 'SHOW_USER_AUTH_MODAL'
export const HIDE_USER_AUTH_MODAL = 'HIDE_USER_AUTH_MODAL'
